name: Flarum Installation

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
        extensions: mbstring, intl, gd, xml, soap, zip, pdo_mysql, curl, json, iconv

    - name: Install Composer dependencies
      run: |
        composer install --no-interaction --no-progress --prefer-dist

    - name: Set up Flarum
      run: |
        cp -R public html
        php flarum install -n --title="lwhsforum" --admin-email=lwh20082021@outlook.com --admin-password=Lwh20080615
