name: Install Flarum

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment
      run: |
        sudo apt-get update
        sudo apt-get install php php-cli php-mbstring git unzip
        php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
        php composer-setup.php --install-dir=/usr/local/bin --filename=composer

    - name: Install Flarum
      run: |
<<<<<<< HEAD
        composer create-project flarum/flarum .
        
=======
        git clone https://github.com/flarum/flarum.git
        cd flarum
        composer install
        php artisan key:generate
        php artisan migrate --seed
>>>>>>> 32b4cd1902411eddff1d4756c9e844a88728abf2
